### ISSUE TITLE
Error running plugins-test using sbt

### ISSUE THREAD

**Issue by ljmf00** [codacy/codacy-plugins-test#96]
The logging framework seems having some issues at the end, when using sbt to run the tests.

Since we run the native image, this is consider a mid level issue. Consider using it to avoid errors.

```
[warn] Thread[pool-2-thread-1,5,main] loading wvlet.log.LogLevel$ after test or run has completed. This is a likely resource leak
2019-11-27 17:12:22,104 pool-2-thread-1 ERROR Unable to unregister MBeans java.lang.NoClassDefFoundError: wvlet/log/LogLevel$
	at wvlet.log.LogRecord$.apply(LogRecord.scala:32)
	at wvlet.log.LogFormatter.format(LogFormat.scala:32)
	at wvlet.log.LogFormatter.format$(LogFormat.scala:29)
	at wvlet.log.LogFormatter$SimpleLogFormatter$.format(LogFormat.scala:120)
	at wvlet.log.ConsoleLogHandler.publish(Handler.scala:13)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.logp(Logger.java:931)
	at com.sun.jmx.mbeanserver.Repository.retrieve(Repository.java:482)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1088)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:345)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:261)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:249)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:340)
	at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:281)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$RegisteredCancellable.run(DefaultShutdownCallbackRegistry.java:109)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: wvlet.log.LogLevel$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at sbt.internal.ManagedClassLoader$ZombieClassLoader.lookupClass(ManagedClassLoader.java:48)
	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 21 more
```

**Comment by lolgab** [comment]
This is fixed now.
It was fixed by adding a workaround in `build.sbt` in [this commit](https://github.com/codacy/codacy-plugins-test/commit/f150591a2796d24ee1c4ab1b29e60ca6593f323a)
